baseURL: "https://rwoll.com/"
title: "rwoll"

googleAnalytics: UA-111464029-1

# [RAW] NOTE: Added this option to prevent the blog section title from
# becoming "Blogs" in list view.
pluralizeListTitles: false

# Syntax Highlighting Options
pygmentsCodefences: true
pygmentsStyle: manni

# Menu Options
sectionPagesMenu: main
menu:
  main:
      # [RAW] NOTE: Home metadata is located in /content/index.md
      - Name: "Blog"
        Identifier: "blog"
        URL: "/blog/"
        Weight: 2

      - Name: "Software Engineering"
        Identifier: "software-engineering"
        URL: "/software-engineering/"
        Weight: 3

      - Name: "Theatre"
        Identifier: "theatre"
        URL: "/theatre/"
        Weight: 4

      - Name: "Contact"
        Identifier: "contact"
        URL: "/contact/"
        Weight: 5

