[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.30"
  ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.30"
  ENV = "preview"
