[build]
  environment = {HUGO_VERSION = "0.30.2"}
  command = "hugo"
  publish = "public"

[context.production.environment]
  ENV = "production"

[context.deploy-preview.environment]
  ENV = "staging"
