[build]
  environment = {HUGO_VERSION = "0.38.2"}
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "staging"
